---

- name: add i386 architecture onto Debian 7
  command: dpkg --add-architecture i386
  when: ansible_os_family == 'Debian' and ansible_distribution_version|int == 7

- name: update the apt package index
  apt:
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'

- name: update the yum package index
  yum:
    name: '*'
    state: latest
  when: ansible_pkg_mgr == 'yum'

- include_vars: '{{ item }}'
  with_first_found:
    - '../vars/{{ ansible_os_family }}-{{ ansible_userspace_bits }}.yml'
    - '../vars/{{ ansible_os_family }}.yml'
    - '../vars/Debian.yml'

- name: install packages
  package:
    name: '{{ item }}'
    state: present
  with_items: steamcmd_packages
